### ISSUE TITLE
Next JS support

### ISSUE THREAD

**Issue by jodik** [dromru/react-photoswipe-gallery#786]
Doesn't work with NextJS, unless:
experimental: {
    esmExternals: "loose",
},

which is experimental.

The error is about incorrect importing using require instead of import (see: https://nextjs.org/docs/messages/import-esm-externals):
![image](https://user-images.githubusercontent.com/9405092/163622467-2fcd5b22-ae5a-458a-9c32-0efea0b153d9.png)

**Comment by irudoy** [comment]
Thanks for reporting! Should be fixed in v2.0.4

**Comment by jodik** [comment]
Thanks for a prompt fix

**Comment by andrew-oko-odion** [comment]
This issue still persists

**Comment by irudoy** [comment]
@andrew-oko-odion can you create isolated reproduction repo for it? I have checked it now, and it works properly with `next@12.1.5`, `photoswipe@5.2.4` and `react-photoswipe-gallery@2.1.0`

**Comment by andrew-oko-odion** [comment]
Its failing with `next@10.0.6` `photoswipe@5.2.4` and `react-photoswipe-gallery@2.1.0`

```
require() of ES modules is not supported.
require() of /Users/drew/workspace/js/eventapp/node_modules/react-photoswipe-gallery/dist/index.js from /Users/drew/workspace/js/eventapp/.next/server/pages/venue.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/drew/workspace/js/eventapp/node_modules/react-photoswipe-gallery/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at eval (webpack-internal:///react-photoswipe-gallery:1:18)
    at Object.react-photoswipe-gallery (/Users/drew/workspace/js/eventapp/.next/server/pages/venue.js:799:1)
    at __webpack_require__ (/Users/drew/workspace/js/eventapp/.next/server/pages/venue.js:23:31)
    at eval (webpack-internal:///./components/PhotoGallery.js:6:82)
    at Module../components/PhotoGallery.js (/Users/drew/workspace/js/eventapp/.next/server/pages/venue.js:198:1)
    at __webpack_require__ (/Users/drew/workspace/js/eventapp/.next/server/pages/venue.js:23:31)
    at eval (webpack-internal:///./pages/venue.js:20:83)
    at Module../pages/venue.js (/Users/drew/workspace/js/eventapp/.next/server/pages/venue.js:612:1)
    at __webpack_require__ (/Users/drew/workspace/js/eventapp/.next/server/pages/venue.js:23:31)
    at /Users/drew/workspace/js/eventapp/.next/server/pages/venue.js:91:18
    at Object.<anonymous> (/Users/drew/workspace/js/eventapp/.next/server/pages/venue.js:94:10) {
  code: 'ERR_REQUIRE_ESM'
```

But upgrading to nextjs seams to work out fine

**Comment by VolrakRutra** [comment]
Does not work on Next.js 12.2.5
